In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('spam.csv')

In [5]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [11]:
df.shape

(5572, 2)

In [13]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.Category,test_size=0.2,random_state=42)

In [19]:
X_train.shape

(4457,)

In [21]:
X_test.shape

(1115,)

In [23]:
X_train

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
                              ...                        
3772    Hi, wlcome back, did wonder if you got eaten b...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860               Did he just say somebody is named tampa
Name: Message, Length: 4457, dtype: object

In [25]:
X_test

3245    Squeeeeeze!! This is christmas hug.. If u lik ...
944     And also I've sorta blown him off a couple tim...
1044    Mmm thats better now i got a roast down me! i’...
2484        Mm have some kanji dont eat anything heavy ok
812     So there's a ring that comes with the guys cos...
                              ...                        
4264    Den only weekdays got special price... Haiz......
2439         I not busy juz dun wan 2 go so early.. Hee..
5556    Yes i have. So that's why u texted. Pshew...mi...
4205    How are you enjoying this semester? Take care ...
4293                                                G.W.R
Name: Message, Length: 1115, dtype: object

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()

In [29]:
emails = [
            'Upto 20% discount reward!',
            'Hey mohan, discount Upto'
         ]
emails_cv=v.fit_transform(emails)
emails_cv

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [33]:
emails_cv.toarray()

array([[1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]], dtype=int64)

In [39]:
v.get_feature_names_out()

array(['20', 'discount', 'hey', 'mohan', 'reward', 'upto'], dtype=object)

In [45]:
v=CountVectorizer()
train_cv=v.fit_transform(X_train)
train_cv

<4457x7701 sparse matrix of type '<class 'numpy.int64'>'
	with 59275 stored elements in Compressed Sparse Row format>

In [47]:
train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [51]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'èn', 'ú1'], dtype=object)

In [53]:
train_cv.shape

(4457, 7701)

In [57]:
pd.DataFrame(train_cv.toarray(),columns=v.get_feature_names_out())

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  02  \
0      0    0       0             0     0     0            0            0   0   
1      0    0       0             0     0     0            0            0   0   
2      0    0       0             0     0     0            0            0   0   
3      0    0       0             0     0     0            0            0   0   
4      0    0       0             0     0     0            0            0   0   
...   ..  ...     ...           ...   ...   ...          ...          ...  ..   
4452   0    0       0             0     0     0            0            0   0   
4453   0    0       0             0     0     0            0            0   0   
4454   0    0       0             0     0     0            0            0   0   
4455   0    0       0             0     0     0            0            0   0   
4456   0    0       0             0     0     0            0            0   0   

      0207  ...  zeros  zhong  zindgi  zoe  zogtorius  zoom  zouk  zyada  èn  \
0        0  ...      0      0       0    0          0     0     0      0   0   
1        0  ...      0      0       0    0          0     0     0      0   0   
2        0  ...      0      0       0    0          0     0     0      0   0   
3        0  ...      0      0       0    0          0     0     0      0   0   
4        0  ...      0      0       0    0          0     0     0      0   0   
...    ...  ...    ...    ...     ...  ...        ...   ...   ...    ...  ..   
4452     0  ...      0      0       0    0          0     0     0      0   0   
4453     0  ...      0      0       0    0          0     0     0      0   0   
4454     0  ...      0      0       0    0          0     0     0      0   0   
4455     0  ...      0      0       0    0          0     0     0      0   0   
4456     0  ...      0      0       0    0          0     0     0      0   0   

      ú1  
0      0  
1      0  
2      0  
3      0  
4      0  
...   ..  
4452   0  
4453   0  
4454   0  
4455   0  
4456   0  

[4457 rows x 7701 columns]

In [59]:
test_cv=v.transform(X_test)
test_cv

<1115x7701 sparse matrix of type '<class 'numpy.int64'>'
	with 13741 stored elements in Compressed Sparse Row format>

In [61]:
test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [65]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(train_cv, y_train)

MultinomialNB()

In [67]:
model.score(test_cv, y_test)

0.9919282511210762

In [69]:
from sklearn.metrics import classification_report

y_pred = model.predict(test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      1.00       966
        spam       1.00      0.94      0.97       149

    accuracy                           0.99      1115
   macro avg       1.00      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

